version: '3'

services:

    fluidsynth:
        build: .
        privileged: true
        container_name: fluidsynth
        restart: unless-stopped
        ports:
            - 7000:7000
        expose:
            - 7000
        networks:
              - internal
        volumes:
            - ./Fluidsynth-Webapp/config.js:/fluidsynthwebapp/config.js
        devices: 
            - '/dev:/dev'

networks:
    internal: